name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean install

    - name: Deploy to Docker Hub
      if: success()
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ ahmedyaar }} --password-stdin
        docker build -t your-dockerhub-username/your-image-name:latest .
        docker push your-dockerhub-username/your-image-name:latest
